CREATE TABLE IF NOT EXISTS application_record (
    id BIGINT PRIMARY KEY,
    code_gender VARCHAR(2),
    flag_own_car VARCHAR(1),
    flag_own_realty VARCHAR(1),
    cnt_children INT,
    amt_income_total FLOAT,
    name_income_type VARCHAR(50),
    name_education_type VARCHAR(50),
    name_family_status VARCHAR(50),
    name_housing_type VARCHAR(50),
    days_birth INT,
    days_employed INT,
    flag_mobil INT,
    flag_work_phone INT,
    flag_phone INT,
    flag_email INT,
    occupation_type VARCHAR(50),
    cnt_fam_members FLOAT,
    approved BOOLEAN,
    approval_date TIMESTAMP,
    risk_score FLOAT,
    risky BOOLEAN,
    external_data_last_checked TIMESTAMP
);
